#!/bin/bash
#set National Geographic Channel's photo of the day as wallpaper

wget --quiet http://photography.nationalgeographic.co.in/photography/photo-of-the-day/ -O /tmp/ngc.html
url=`grep -o -m 1 images.nationalgeographic.com/wpf/media-live/photos/.*x.*jpg /tmp/ngc.html` 
echo $url
wget --quiet http://$url -O /tmp/pic.jpg
gsettings set org.gnome.desktop.background picture-uri file:///tmp/pic.jpg

